# the filter currently checks for words that are 3 or more characters.
---
4r5e: *r5*
5h1t: 5h*t
5hit: 5h*t
a55: "*55"
a_s_s: "*_s_s"
anal: "*n*l"
anus: "*n*s"
ar5e: "*r5*"
arrse: "*rrs*"
arse: "*rs*"
ass-fucker: "*ss-f*ck*r"
ass: "*ss"
asses: "*ss*s"
assfucker: "*ssf*ck*r"
assfukka: "*ssf*kk*"
asshole: "*ssh*l*"
assholes: "*ssh*l*s"
asswhole: "*sswh*l*"
b!tch: b!tch
b00bs: b**bs
b17ch: b*7ch
b1tch: b*tch
ballbag: b*llb*g
balls: b*lls
ballsack: b*lls*ck
bastard: b*st*rd
beastial: b**st**l
beastiality: b**st**l*ty
beastility: b**st*l*ty
bellend: b*ll*nd
bestial: b*st**l
bestiality: b*st**l*ty
bi+ch: b*+ch
biatch: b**tch
bitch: b*tch
bitcher: b*tch*r
bitchers: b*tch*rs
bitches: b*tch*s
bitchin: b*tch*n
bitching: b*tch*ng
bloody: bl**dy
blowjob: bl*wj*b
blowjobs: bl*wj*bs
boiolas: b***l*s
bollock: b*ll*ck
bollok: b*ll*k
boner: b*n*r
boob: b**b
boobs: b**bs
booobs: b***bs
boooobs: b****bs
booooobs: b*****bs
booooooobs: b*******bs
breasts: br**sts
buceta: b*c*t*
bugger: b*gg*r
bullshit: b*llsh*t
bum: b*m
butt: b*tt
butthole: b*tth*l*
buttmuch: b*ttm*ch
buttplug: b*ttpl*g
c0ck: c*ck
c0cksucker: c*cks*ck*r
cawk: c*wk
chink: ch*nk
cipa: c*p*
cl1t: cl*t
clit: cl*t
clitoris: cl*t*r*s
clits: cl*ts
cnut: cn*t
cock-sucker: c*ck-s*ck*r
cock: c*ck
cockface: c*ckf*c*
cockhead: c*ckh**d
cockmunch: c*ckm*nch
cockmuncher: c*ckm*nch*r
cocks: c*cks
cocksuck: c*cks*ck
cocksucked: c*cks*ck*d
cocksucker: c*cks*ck*r
cocksucking: c*cks*ck*ng
cocksucks: c*cks*cks
cocksuka: c*cks*k*
cocksukka: c*cks*kk*
cok: c*k
cokmuncher: c*km*nch*r
coksucka: c*ks*ck*
coon: c**n
cox: c*x
crap: cr*p
cum: c*m
cummer: c*mm*r
cumming: c*mm*ng
cums: c*ms
cumshot: c*msh*t
cunilingus: c*n*l*ng*s
cunillingus: c*n*ll*ng*s
cunnilingus: c*nn*l*ng*s
cunt: c*nt
cuntlick: c*ntl*ck
cuntlicker: c*ntl*ck*r
cuntlicking: c*ntl*ck*ng
cunts: c*nts
cyalis: cy*l*s
cyberfuc: cyb*rf*c
cyberfuck: cyb*rf*ck
cyberfucked: cyb*rf*ck*d
cyberfucker: cyb*rf*ck*r
cyberfuckers: cyb*rf*ck*rs
cyberfucking: cyb*rf*ck*ng
d1ck: d*ck
damn: d*mn
dick: d*ck
dickhead: d*ckh**d
dildo: d*ld*
dildos: d*ld*s
dink: d*nk
dinks: d*nks
dirsa: d*rs*
dlck: d*ck
dog-fucker: d*g-f*ck*r
doggin: d*gg*n
dogging: d*gg*ng
donkeyribber: d*nk*yr*bb*r
doosh: d**sh
duche: d*ch*
dyke: dyk*
ejaculate: "*j*c*l*t*"
ejaculated: "*j*c*l*t*d"
ejaculates: "*j*c*l*t*s"
ejaculating: "*j*c*l*t*ng"
ejaculatings: "*j*c*l*t*ngs"
ejaculation: "*j*c*l*t**n"
ejakulate: "*j*k*l*t*"
f4nny: f*nny
f_u_c_k: f_*_c_k
fag: f*g
fagging: f*gg*ng
faggitt: f*gg*tt
faggot: f*gg*t
faggs: f*ggs
fagot: f*g*t
fagots: f*g*ts
fags: f*gs
fanny: f*nny
fannyflaps: f*nnyfl*ps
fannyfucker: f*nnyf*ck*r
fanyy: f*nyy
fart: f*rt
farted: f*rt*d
farting: f*rt*ng
fartings: f*rt*ngs
farts: f*rts
farty: f*rty
fatass: f*t*ss
fcuk: fc*k
fcuker: fc*k*r
fcuking: fc*k*ng
feck: f*ck
fecker: f*ck*r
felatio: f*l*t**
felching: f*lch*ng
fellate: f*ll*t*
fellatio: f*ll*t**
fingerfuck: f*ng*rf*ck
fingerfucked: f*ng*rf*ck*d
fingerfucker: f*ng*rf*ck*r
fingerfuckers: f*ng*rf*ck*rs
fingerfucking: f*ng*rf*ck*ng
fingerfucks: f*ng*rf*cks
fistfuck: f*stf*ck
fistfucked: f*stf*ck*d
fistfucker: f*stf*ck*r
fistfuckers: f*stf*ck*rs
fistfucking: f*stf*ck*ng
fistfuckings: f*stf*ck*ngs
fistfucks: f*stf*cks
flange: fl*ng*
fook: f**k
fooker: f**k*r
fuck: f*ck
fucka: f*ck*
fucked: f*ck*d
fucker: f*ck*r
fuckers: f*ck*rs
fuckhead: f*ckh**d
fuckheads: f*ckh**ds
fuckin: f*ck*n
fucking: f*ck*ng
fuckings: f*ck*ngs
fuckingshitmotherfucker: f*ck*ngsh*tm*th*rf*ck*r
fuckme: f*ckm*
fucks: f*cks
fuckwhit: f*ckwh*t
fuckwit: f*ckw*t
fudgepacker: f*dg*p*ck*r
fuk: f*k
fuker: f*k*r
fukker: f*kk*r
fukkin: f*kk*n
fuks: f*ks
fukwhit: f*kwh*t
fukwit: f*kw*t
fux0r: f*x*r
fux: f*x
gangbang: g*ngb*ng
gangbanged: g*ngb*ng*d
gangbangs: g*ngb*ngs
gaylord: g*yl*rd
gaysex: g*ys*x
goatse: g**ts*
god-dam: g*d-d*m
god-damned: g*d-d*mn*d
goddamn: g*dd*mn
goddamned: g*dd*mn*d
hardcoresex: h*rdc*r*s*x
hell: h*ll
heshe: h*sh*
hoar: h**r
hoare: h**r*
hoer: h**r
homo: h*m*
hore: h*r*
horniest: h*rn**st
horny: h*rny
hotsex: h*ts*x
jack-off: j*ck-*ff
jackoff: j*ck*ff
jap: j*p
jerk-off: j*rk-*ff
jism: j*sm
jiz: j*z
jizm: j*zm
jizz: j*zz
kawk: k*wk
knob: kn*b
knobead: kn*b**d
knobed: kn*b*d
knobend: kn*b*nd
knobhead: kn*bh**d
knobjocky: kn*bj*cky
knobjokey: kn*bj*k*y
kock: k*ck
kondum: k*nd*m
kondums: k*nd*ms
kum: k*m
kumer: k*mm*r
kummer: k*mm*r
kumming: k*mm*ng
kums: k*ms
kunilingus: k*n*l*ng*s
l3i+ch: l**+ch
l3itch: l**tch
labia: l*b**
lmfao: lmf**
lust: l*st
lusting: l*st*ng
m0f0: m*f*
m0fo: m*f*
m45terbate: m*5t*rb*t*
ma5terb8: m*5t*rb*
ma5terbate: m*5t*rb*t*
masochist: m*s*ch*st
master-bate: m*st*r-b*t*
masterb8: m*st*rb*
masterbat*: m*st*rb*t*
masterbat3: m*st*rb*t*
masterbate: m*st*rb*t*
masterbation: m*st*rb*t**n
masterbations: m*st*rb*t**ns
masturbate: m*st*rb*t*
mo-fo: m*-f*
mof0: m*f*
mofo: m*f*
mothafuck: m*th*f*ck
mothafucka: m*th*f*ck*
mothafuckas: m*th*f*ck*s
mothafuckaz: m*th*f*ck*z
mothafucked: m*th*f*ck*d
mothafucker: m*th*f*ck*r
mothafuckers: m*th*f*ck*rs
mothafuckin: m*th*f*ck*n
mothafucking: m*th*f*ck*ng
mothafuckings: m*th*f*ck*ngs
mothafucks: m*th*f*cks
motherfuck: m*th*rf*ck
motherfucked: m*th*rf*ck*d
motherfucker: m*th*rf*ck*r
motherfuckers: m*th*rf*ck*rs
motherfuckin: m*th*rf*ck*n
motherfucking: m*th*rf*ck*ng
motherfuckings: m*th*rf*ck*ngs
motherfuckka: m*th*rf*ckk*
motherfucks: m*th*rf*cks
muff: m*ff
mutha: m*th*
muthafecker: m*th*f*ck*r
muthafuckker: m*th*f*ckk*r
muther: m*th*r
mutherfucker: m*th*rf*ck*r
n1gga: n*gg*
n1gger: n*gg*r
nazi: n*z*
niger: n*gg*r
nigg3r: n*gg*r
nigg4h: n*gg*h
nigga: n*gg*
niggah: n*gg*h
niggas: n*gg*s
niggaz: n*gg*z
nigger: n*gg*r
niggers: n*gg*rs
nob: n*b
nobhead: n*bh**d
nobjocky: n*bj*cky
nobjokey: n*bj*k*y
numbnuts: n*mbn*ts
nutsack: n*ts*ck
orgasim: "*rg*s*m"
orgasims: "*rg*s*ms"
orgasm: "*rg*sm"
orgasms: "*rg*sms"
p0rn: p*rn
pawn: p*wn
pecker: p*ck*r
penis: p*n*s
penisfucker: p*n*sf*ck*r
phonesex: ph*n*s*x
phuck: ph*ck
phuk: ph*k
phuked: ph*k*d
phuking: ph*k*ng
phukked: ph*kk*d
phukking: ph*kk*ng
phuks: ph*ks
phuq: ph*q
pigfucker: p*gf*ck*r
pimpis: p*mp*s
pis: p*ss
pises: p*ss*s
pisin: p*ss*n
pising: p*ss*ng
pisof: p*ss*ff
piss: p*ss
pissed: p*ss*d
pisser: p*ss*r
pissers: p*ss*rs
pisses: p*ss*s
pissflaps: p*ssfl*ps
pissin: p*ss*n
pissing: p*ss*ng
pissoff: p*ss*ff
poop: p**p
porn: p*rn
porno: p*rn*
pornography: p*rn*gr*phy
pornos: p*rn*s
prick: pr*ck
pricks: pr*cks
pron: pr*n
pube: p*b*
pusies: p*ss**s
pusse: p*ss*
pussi: p*ss*
pussies: p*ss**s
pussy: p*ssy
pussys: p*ssys
pusy: p*ssy
pusys: p*ssys
rectum: r*ct*m
retard: r*t*rd
rimjaw: r*mj*w
rimming: r*mm*ng
s.o.b.: s.*.b.
s_h_i_t: s_h_*_t
sadist: s*d*st
schlong: schl*ng
screwing: scr*w*ng
scroat: scr**t
scrote: scr*t*
scrotum: scr*t*m
semen: s*m*n
sex: s*x
sh!+: sh*+
sh!t: sh*t
sh1t: sh*t
shag: sh*g
shagger: sh*gg*r
shaggin: sh*gg*n
shagging: sh*gg*ng
shemale: sh*m*l*
shi+: sh*+
shit: sh*t
shitdick: sh*td*ck
shite: sh*t*
shited: sh*t*d
shitey: sh*t*y
shitfuck: sh*tf*ck
shitfull: sh*tf*ll
shithead: sh*th**d
shiting: sh*t*ng
shitings: sh*t*ngs
shits: sh*ts
shitted: sh*tt*d
shitter: sh*tt*r
shitters: sh*tt*rs
shitting: sh*tt*ng
shittings: sh*tt*ngs
shitty: sh*tty
shity: sh*tty
skank: sk*nk
slut: sl*t
sluts: sl*ts
smegma: sm*gm*
smut: sm*t
snatch: sn*tch
son-of-a-bitch: s*n-*f-*-b*tch
spac: sp*c
spunk: sp*nk
t1tt1e5: t*tt**5
t1tties: t*tt**s
teets: t**ts
teez: t**z
testical: t*st*c*l
testicle: t*st*cl*
tit: t*t
titfuck: t*tf*ck
tits: t*ts
titt: t*tt
tittie5: t*tt**5
tittiefucker: t*tt**f*ck*r
titties: t*tt**s
tittyfuck: t*ttyf*ck
tittywank: t*ttyw*nk
titwank: t*tw*nk
tosser: t*ss*r
turd: t*rd
tw4t: tw*t
twat: tw*t
twathead: tw*th**d
twatty: tw*tty
twunt: tw*nt
twunter: tw*nt*r
v14gra: v**gr*
v1gra: v*gr*
vagina: v*g*n*
viagra: v**gr*
vulva: v*lv*
w00se: w**s*
wang: w*ng
wank: w*nk
wanker: w*nk*r
wanky: w*nky
whoar: wh**r
whore: wh*r*
willies: w*ll**s
willy: w*lly
xrated: xr*t*d
xxx: xxx
